name: webf_example
description: Demonstrates how to use the webf plugin.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  example_rust_builder:
    path: rust_builder

  webf:
  webf_callf:
  webf_audio_player:
  webf_websocket:

dependency_overrides:
  webf:
    path: ../
  webf_callf:
    path: ../../../plugins/packages/webf_callf/callf
  webf_audio_player:
    path: ../../../plugins/packages/audio
  webf_websocket:
    path: ../../../plugins/packages/webf_websocket

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AlibabaPuHuiTi
      fonts:
        - asset: fonts/Alibaba-PuHuiTi-Regular.ttf
        - asset: fonts/Alibaba-PuHuiTi-Light.ttf
          weight: 300
        - asset: fonts/Alibaba-PuHuiTi-Medium.ttf
          weight: 500
        - asset: fonts/Alibaba-PuHuiTi-Bold.ttf
          weight: 700
        - asset: fonts/Alibaba-PuHuiTi-Heavy.ttf
          weight: 900
    - family: AlibabaSans
      fonts:
        - asset: fonts/AlibabaSans-Regular.otf
        - asset: fonts/AlibabaSans-Italic.otf
          style: italic
        - asset: fonts/AlibabaSans-Light.otf
          weight: 300
        - asset: fonts/AlibabaSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/AlibabaSans-Medium.otf
          weight: 500
        - asset: fonts/AlibabaSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/AlibabaSans-Bold.otf
          weight: 700
        - asset: fonts/AlibabaSans-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/AlibabaSans-Heavy.otf
          weight: 900
        - asset: fonts/AlibabaSans-HeavyItalic.otf
          weight: 900
          style: italic
    - family: AlibabaSans-Black
      fonts:
        - asset: fonts/AlibabaSans-Black.otf
