include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_assignment: error
    prefer_single_quotes: error
    slash_for_doc_comments: error
    unnecessary_string_escapes: error
    close_sinks: error
    cancel_subscriptions: error
    prefer_contains: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    file_names: error
  exclude:
    - "**/.symlink"
    - "**/flutter/ephemeral"
